kermitt2/grobid

- grobid-core/src/main/java/org/grobid/core/engines/ReferenceSegmenterParser.java
- grobid-core/src/main/java/org/grobid/core/features/FeaturesVectorReferenceSegmenter.java
Thanks for the guide through the code!
> Indentation feature for ReferenceSegmenter

- pom.xml
Hi @kermitt2, 
Please have a look at the changes. I will be doing the same for the dependencies you mentioned in your comments to the issue. 
I can't complete a release myself as I do not have write commits to the repository (required to 'tag' a release and commit the tag) so I hope that this pull request is a firm move towards you having an automated, Maven friendly workflow for publishing Grobid to the masses :)
Thanks!
> Fix for Grobid #59 - Publishing to Maven Central

- grobid-core/src/main/java/org/grobid/core/document/TEIFormater.java
- grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java
- grobid-core/src/main/java/org/grobid/core/engines/Engine.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
- grobid-core/src/main/java/org/grobid/core/engines/ProcessEngine.java
- grobid-core/src/main/java/org/grobid/core/engines/Segmentation.java
- grobid-core/src/main/java/org/grobid/core/engines/config/GrobidAnalysisConfig.java
- grobid-core/src/main/java/org/grobid/core/engines/config/InvalidGrobidAnalysisConfig.java
- grobid-core/src/test/java/org/grobid/core/engines/EngineTest.java
- grobid-core/src/test/java/org/grobid/core/test/TestFullTextParser.java
- grobid-core/src/test/java/org/grobid/core/test/TestHeaderParser.java
- grobid-core/src/test/java/org/grobid/core/test/TestReferencesParser.java
- grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java
- grobid-trainer/src/main/java/org/grobid/trainer/evaluation/PubMedCentralEvaluation.java
Simpler management of parameters.
> refactoring to use GrobidAnalysisConfig

- grobid-core/pom.xml
- grobid-core/src/main/java/org/grobid/core/data/BibDataSet.java
- grobid-core/src/main/java/org/grobid/core/document/Document.java
- grobid-core/src/main/java/org/grobid/core/document/TEICounters.java
- grobid-core/src/main/java/org/grobid/core/document/TEIFormater.java
- grobid-core/src/main/java/org/grobid/core/document/xml/NodeChildrenIterator.java
- grobid-core/src/main/java/org/grobid/core/document/xml/NodesIterator.java
- grobid-core/src/main/java/org/grobid/core/document/xml/XmlBuilderUtils.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/engines/TaggingLabel.java
- grobid-core/src/main/java/org/grobid/core/engines/tagging/GenericTaggerUtils.java
- grobid-core/src/main/java/org/grobid/core/layout/Block.java
- grobid-core/src/main/java/org/grobid/core/layout/BoundingBox.java
- grobid-core/src/main/java/org/grobid/core/sax/PDF2XMLSaxParser.java
- grobid-core/src/main/java/org/grobid/core/tokenization/LabeledTokensContainer.java
- grobid-core/src/main/java/org/grobid/core/tokenization/TaggingTokenCluster.java
- grobid-core/src/main/java/org/grobid/core/tokenization/TaggingTokenClusteror.java
- grobid-core/src/main/java/org/grobid/core/tokenization/TaggingTokenSynchronizer.java
- grobid-core/src/main/java/org/grobid/core/utilities/BoundingBoxCalculator.java
- grobid-core/src/main/java/org/grobid/core/utilities/LayoutTokensUtil.java
- grobid-core/src/main/java/org/grobid/core/utilities/XQueryProcessor.java
- grobid-core/src/main/java/org/grobid/core/utilities/matching/ReferenceMarkerMatcher.java
- grobid-core/src/main/java/org/grobid/core/visualization/AnnotationUtil.java
- grobid-core/src/main/java/org/grobid/core/visualization/BlockVisualizer.java
- grobid-core/src/main/java/org/grobid/core/visualization/CitationsVisualizer.java
- grobid-core/src/main/resources/xq/vector-coords.xq
- grobid-core/src/test/java/org/grobid/core/engines/EngineTest.java
Utilities for syncing, clustering tokens that would avoid code duplication and incapsulate synchronization logic
Additionally different types of markers are now created in place that eliminates the need for TEI syncronization (that failed in a number of cases)
> Layout utils

- grobid-core/src/test/java/org/grobid/core/document/TEIFormaterTest.java
- grobid-service/src/main/webapp/WEB-INF/web.xml
Test PullRequest with package name fix and xml header for web.xml.
> Name package fixed

- grobid-core/src/test/java/org/grobid/core/engines/EngineTest.java
- grobid-trainer/pom.xml
- grobid-trainer/src/main/java/org/grobid/trainer/LabelStat.java
- grobid-trainer/src/main/java/org/grobid/trainer/Stats.java
- grobid-trainer/src/main/java/org/grobid/trainer/Trainer.java
- grobid-trainer/src/main/java/org/grobid/trainer/evaluation/EvaluationUtilities.java
- grobid-trainer/src/main/java/org/grobid/trainer/evaluation/PubMedCentralEvaluation.java
This may be too big of a change...
I was trying to understand how Grobid evaluates a model, and the best way I found to do that was to refactor the code.  It produces the same results in my *limited* testing.
> Rework the way stats are calculated

- grobid-service/src/main/java/org/grobid/service/GrobidPathes.java
- grobid-service/src/main/java/org/grobid/service/GrobidRestService.java
- grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessGeneric.java
- grobid-service/src/main/webapp/WEB-INF/web.xml
- grobid-service/src/test/java/org/grobid/service/tests/GrobidRestServiceTest.java
This PR should resolve https://github.com/kermitt2/grobid/issues/155
> Added RESTfull endpoint for getting grobid version

- grobid-core/src/main/java/org/grobid/core/sax/CrossrefUnixrefSaxParser.java
Without that flag the document DOI is overwrited by the doi
of citations list.
> Add flag to sinalize the end of doi data.

- Dockerfile
> added multi step dockerfile for 0.5.0 version

- build.gradle
- grobid-service/src/test/java/org/grobid/service/tests/GrobidRestServiceTest.java
- dropwizard (to latest version)
- pdfbox (to latest minor version)
> Updated dependencies

- grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java
- grobid-core/src/test/java/org/grobid/core/utilities/GrobidPropertiesTest.java
- grobid-home/config/grobid.properties
- grobid-service/src/test/resources/setup/config/grobid.properties
> Use available threads when nb threads is zero

- doc/Troubleshooting.md
> Add workaround for Java version to Troubleshooting

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Updated to gradle 5 and updated shadow plugin. #432 
I've tested build and running some gradle tasks and it seems to work fine.
> migration to gradle 5

- grobid-core/src/main/java/org/grobid/core/jni/JEPThreadPool.java
- grobid-core/src/main/java/org/grobid/core/jni/PythonEnvironmentConfig.java
- grobid-core/src/main/java/org/grobid/core/jni/PythonVirtualEnvConfig.java
- grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java
this is work-in-progress...
Trying to get JEP to work locally (Linux).
See #409 (although the issue is related to macOS)
/cc @kermitt2 @lfoppiano
> [wip] fix jep

- doc/training/Bibliographical-references.md
- grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java
- grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java
> consistency in DOI capitalization (not 'doi') in XML

- grobid-core/src/main/java/org/grobid/core/visualization/CitationsVisualizer.java
> use https:// in generated links (not http://)

- grobid-core/src/main/java/org/grobid/core/jni/JEPThreadPool.java
- grobid-core/src/main/java/org/grobid/core/jni/PythonEnvironmentConfig.java
- grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java
further revisions... see comments below...
> revise jep v2

- grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java
- grobid-home/config/grobid.properties
This is what got lost in the merge
/cc @lfoppiano
> revise jep v3

- grobid-core/src/main/java/org/grobid/core/engines/Engine.java
Logs the full exception rather than just the message.
This helped to narrow down #470
> create training data: log full exception

- grobid-core/src/main/java/org/grobid/core/engines/Engine.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java
- grobid-core/src/main/java/org/grobid/core/utilities/GrobidPropertyKeys.java
- grobid-core/src/test/java/org/grobid/core/utilities/GrobidPropertiesTest.java
see discussion in #476
/cc @lfoppiano @kermitt2
> optionally disable header heuristics

- grobid-trainer/src/main/java/org/grobid/trainer/AbstractTrainer.java
> Fixes n fold evaluation

- doc/Introduction.md
Didn't want to go without institution.
Thank you for adding me there.
> Add koppor's "institution"

- build.gradle
- grobid-service/src/main/java/org/grobid/service/main/GrobidServiceApplication.java
> feat: support export metrics as prometheus format

- grobid-core/src/main/java/org/grobid/core/factory/GrobidPoolingFactory.java
Cherry-pick (with fix) from #771
> migrated to typed engineFactory

- .circleci/config.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- update to gradle 7.1.1
- restore the coveralls reports
- various cleanup
> Updates on the build 

- doc/Grobid-service.md
- grobid-core/src/main/java/org/grobid/core/engines/Engine.java
- grobid-service/src/main/java/org/grobid/service/GrobidPaths.java
- grobid-service/src/main/java/org/grobid/service/GrobidRestService.java
- grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessString.java
Add a web service to process a list of reference strings. 
It can be tested with the python client, branch https://github.com/kermitt2/grobid_client_python/tree/processCitationList
Documentation: https://grobid.readthedocs.io/en/processcitationlist/Grobid-service/#apiprocesscitationlist
> Process citation list

- grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
- grobid-core/src/main/java/org/grobid/core/utilities/matching/ReferenceMarkerMatcher.java
> Fix #811 - issue with sentence element bounding box

- grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java
- grobid-core/src/test/java/org/grobid/core/data/BiblioItemTest.java
Closes https://github.com/kermitt2/grobid/issues/848
> Escape more identifiers, including ISSN

- grobid-core/src/main/java/org/grobid/core/utilities/LayoutTokensUtil.java
- grobid-core/src/test/java/org/grobid/core/utilities/LayoutTokensUtilTest.java
This should resolve issue #933
> Avoid dehypenisation when the hypen is superscript or subscript

- doc/Grobid-batch.md
- grobid-core/src/main/java/org/grobid/core/engines/ProcessEngine.java
- grobid-core/src/main/java/org/grobid/core/main/batch/GrobidMain.java
- grobid-core/src/main/java/org/grobid/core/main/batch/GrobidMainArgs.java
> Add parameter to generate automatically xml:id for elements in the TEI XML result for the batch command line

- grobid-core/src/main/java/org/grobid/core/utilities/UnicodeUtil.java
> Extend DASH_PATTERN to cover a particular minus sign 

- grobid-core/src/main/java/org/grobid/core/visualization/CitationsVisualizer.java
Found this while testing #1028, it happened when the getEquations() is null. It happened with this PDF 😅 
[Curriculum_Vitae.pdf](https://github.com/kermitt2/grobid/files/11683013/Curriculum_Vitae.pdf)
> avoid 500 when the equations are null

- CHANGELOG.md
- Dockerfile.delft
- build.gradle
- doc/Deep-Learning-models.md
- doc/Frequently-asked-questions.md
- doc/Grobid-batch.md
- doc/Grobid-docker.md
- doc/Grobid-java-library.md
- doc/Grobid-service.md
- doc/Install-Grobid.md
- doc/Notes-grobid-developers.md
- doc/Run-Grobid.md
- gradle.properties
- grobid-core/src/main/java/org/grobid/core/engines/Engine.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-service/src/main/java/org/grobid/service/GrobidPaths.java
- grobid-service/src/main/java/org/grobid/service/GrobidRestService.java
- grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java
Prepare everything for next release.
> Pre release 0.8.0

- grobid-core/src/main/java/org/grobid/core/document/OPSService.java
Fixes [https://github.com/kermitt2/grobid/security/code-scanning/41](https://github.com/kermitt2/grobid/security/code-scanning/41)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert #41: Resolving XML external entity in user-controlled data

- Dockerfile.delft
> Fix missing libcublas-12

- .github/ISSUE_TEMPLATE/general-report.md
Improve issue template, I cannot test it on a separate branch.
> improve issue template

- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/lexicon/Lexicon.java
- grobid-core/src/main/java/org/grobid/core/utilities/TextUtilities.java
- grobid-core/src/test/java/org/grobid/core/lexicon/LexiconTest.java
We added a new regex that provide an alternative matching for the URLs (I did not dear to modify the body of the existing one)
> Update the URL regexes matching urls starting with a vulgar www.

- Readme.md
- doc/Grobid-batch.md
https://github.com/miku/grobidclient is a Go grobid client library that comes with a CLI and allows to process a single file or a directory of files in parallel. It also includes conversion utilities to turn TEI-XML to JSON, similar to https://pypi.org/project/grobid-tei-xml/ package.
> docs: link to go client library for grobid

- grobid-trainer/resources/dataset/header/corpus/tei/4EE4CA4527C3CBD0A238BC82EF137E0445AEE879.training.header.tei.xml
as in title, more info in #1126
> Move the period outside the <idno> tag

- build.gradle
See https://github.com/kermitt2/grobid/security/advisories/GHSA-4r7x-rm2j-vg2h
> Fix for CVE in CommonsIO

- grobid-trainer/src/main/java/org/grobid/trainer/evaluation/EndToEndEvaluation.java
This PR fixes the flavor parameter for the End2End evaluation
> Fix flavor parameter

- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
Cleanup the flavor / specialist processing
> Avoid collecting text twice

- .github/workflows/ci-build-manual-eval.yml
- Dockerfile.evaluation
- grobid-home/config/grobid-evaluation.yaml
This PR creates a new image already configured and ready to be used for running the end to end evaluation on the 4 repositories.
> Enable running end 2 end evaluation via a docker container

- grobid-home/config/grobid-evaluation.yaml
- grobid-home/config/grobid-full.yaml
As DL for patent processing is available, use it in full and eval images.
> Use DL models for patent processing for full and eval images

- grobid-core/src/main/java/org/grobid/core/GrobidModels.java
- grobid-core/src/test/java/org/grobid/core/GrobidModelsTest.java
This PR introduce a fallback toward standard when flavor not available
> Fallback flavor to standard

- grobid-core/src/main/java/org/grobid/core/data/Figure.java
- grobid-core/src/main/java/org/grobid/core/data/Table.java
- grobid-core/src/main/java/org/grobid/core/document/Document.java
- grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
This PR updates the node structure of the newly collected discarded text, placing them into `<p>` and `<s>`
> refine notes elements

- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/layout/PDFAnnotation.java
- grobid-core/src/main/java/org/grobid/core/utilities/TextUtilities.java
> Avoid NPE when iterating over annotations that might have null bounding Boxes

- grobid-core/src/main/java/org/grobid/core/utilities/TextUtilities.java
This PR remove some old code that is not relevant anymore as the images are managed by a different component
> Remove filters by image extensions 

- grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
- grobid-core/src/main/java/org/grobid/core/engines/MonographParser.java
- grobid-core/src/main/java/org/grobid/core/engines/ReferenceSegmenterParser.java
- grobid-core/src/main/java/org/grobid/core/engines/Segmentation.java
- grobid-core/src/main/java/org/grobid/core/lexicon/FastMatcher.java
- grobid-core/src/main/java/org/grobid/core/lexicon/Lexicon.java
- grobid-core/src/main/java/org/grobid/core/tokenization/LabeledTokensContainer.java
- grobid-core/src/test/java/org/grobid/core/engines/EngineTest.java
- grobid-core/src/test/java/org/grobid/core/sax/PDFALTOSaxHandlerTest.java
This PR: 
- resolve some deprecations
- improve opening/closing resources for fast matcher
> Resolve some deprecations 

- grobid-core/src/main/java/org/grobid/core/document/Document.java
- grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
- grobid-core/src/test/kotlin/org/grobid/core/document/DocumentTest.kt
- grobid-core/src/test/kotlin/org/grobid/core/engines/FullTextParserTest.kt
.. #1264 follow up. This should solve the second part of issue #1252
> Revert text that does not belong to graphics as paragraph instead of discarding it

- Dockerfile.evaluation
- grobid-service/src/main/java/org/grobid/service/GrobidRestService.java
The e2e docker image evaluation was buggy. This PR should fix it making it fully dependent on the source revision
> Revise Docker image for the E2E evaluation
