kermitt2/grobid

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java, grobid-core/src/main/java/org/grobid/core/utilities/TextUtilities.java
Dear Grobid team,
I had some trouble with Grobid not properly escaping XML special characters in the `xml:id` attribute when generating `biblStruct`s.
Also I noticed a typo in the part of the `TextUtilities.HTMLEncode` method that tries to prevent double encoding of HTML entities (it was checking for `&quote;` instead of `&quot;`.
Let me know what you think!
All the best,
Fabian
=> improve handling of HTML entities

grobid-home/lexicon/countries/CountryCodes.xml
It would be useful to add 'Peoples R China' as an additional English alternative name to the country code lexicon. The extracted affiliation strings from Web of Science seem to contain this name quite often.
=> Add an alternative name for China to country codes

grobid-home/lexicon/countries/CountryCodes.xml
It would be useful to add the alternative names for
- Belarus
- Ivory Coast
- United Arab Emirates
- Papua New Guinea
- Reunion
- Northern Ireland
to the country code lexicon. The extracted affiliation strings from Web of Science seem to contain this names in some cases.
=> add alternative country names to country codes

Dockerfile, doc/Grobid-docker.md
When I tried to run GROBID inside Docker, there was a problem with creating /tmp directory.
Stacktrace:
> 2017-01-06 02:17:32.208:INFO::main: Logging initialized @344ms
2017-01-06 02:17:32.428:INFO:oejs.SetUIDListener:main: Setting umask=02
2017-01-06 02:17:32.438:INFO:oejs.SetUIDListener:main: Opened ServerConnector@35f983a6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-01-06 02:17:32.438:INFO:oejs.SetUIDListener:main: Setting GID=999
2017-01-06 02:17:32.439:INFO:oejs.SetUIDListener:main: Setting UID=999
2017-01-06 02:17:32.442:INFO:oejs.Server:main: jetty-9.3.15.v20161220
2017-01-06 02:17:32.464:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
2017-01-06 02:17:35.134:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1833ms
Jan …
=> Fixed ResourceException when running GROBID inside Docker

grobid-core/src/main/java/org/grobid/core/engines/ProcessEngine.java
Currently grobid fails to create intermediate output subfolders during
recursive batch processing if the corresponding input subfolder does
not contain any PDFs.
This leads to FileNotFound Exceptions for PDFs deeper in the directory
tree, as the directory tree on the output side is incomplete.
Changing File.mkdir() to File.mkdirs() creates all potential missing
intermediate folders.
The following shell script allows for easy replication:
```
#! /bin/bash
(($# <= 2)) || { echo "Usage: $0 <grobid_project_directory> <test_here>"; exit 1; }
GROBID_DIR="${1:-$HOME/Projects/misc/grobid}"
if [ ! -d "$GROBID_DIR" ]; then
echo "Error: Grobid base directory does not exist!"
exit 1
fi
GROBID_HOME="$GROBID_DIR/grobid-home"
GROBID_CORE="$GROBID_DIR/grobid-core" …
```
=> Fixing recursive processing with empty subfolders.

grobid-core/src/main/java/org/grobid/core/engines/DateParser.java, grobid-core/src/test/java/org/grobid/core/engines/DateParserTest.java
There are two things in this commit:
1. Patterns are simplified to change (J|j) to [Jj] which accordingly to Intellij should work faster :)
2. Months patterns are matched till the end of string, this would prevent the test "testMayAndMarchOverlap" to fail for *May* because it would match *ma* for Pattern *mar* first.
=> Fix for the May/March ambiguity.

grobid-core/pom.xml, grobid-service/pom.xml, grobid-trainer/pom.xml, pom.xml
The manifest would look something like:
Manifest-Version: 1.0
SCM-Description: grobid-parent-0.4.1-138-g2ab2b23-dirty
SCM-Revision: 2ab2b23456c9a8cc21c6f3bfbae8989bfc99eba5
Built-By: userID
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_131
It would help to identify the snapshot version which was from sources by a git revision id.
=> Provide git info in the MANIFEST.MF

grobid-core/src/main/java/org/grobid/core/lang/Language.java, grobid-core/src/test/java/org/grobid/core/lang/LanguageTest.java
Exception occurs for some documents:
org.grobid.core.utilities.LanguageUtilities: Cannot detect language because of: 
org.grobid.core.exceptions.GrobidException: [GENERAL] Language id should consist of two or three letters, but was: zh-tw
=> Fix 'zh-tw' language detection.

grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java
If getPages fails with an exception, document is not closed:
> at org.apache.pdfbox.pdmodel.PDPageTree.<init>(PDPageTree.java:75)
at org.apache.pdfbox.pdmodel.PDDocumentCatalog.getPages(PDDocumentCatalog.java:128)
at org.apache.pdfbox.pdmodel.PDDocument.getNumberOfPages(PDDocument.java:1262)
=> Problematic PDFs could leak resources.

grobid-core/pom.xml, grobid-service/pom.xml, pom.xml
SLF4j implementation should not be a part of the Grobid Core - the implementation is provided by the user of the library.
=> Remove slf4j implementation from the Grobid Core.

grobid-core/src/main/java/org/grobid/core/utilities/BibDataSetContextExtractor.java, grobid-core/src/test/java/org/grobid/core/utilities/BibDataSetContextExtractorTest.java, grobid-core/src/test/resources/test/tei-escape.xml
I've been seeing the following error fairly frequently: ```
! java.lang.IllegalArgumentException: Illegal group reference                                                    
! at java.util.regex.Matcher.appendReplacement(Matcher.java:857)                                                 
! at java.util.regex.Matcher.replaceAll(Matcher.java:955)                                                        
! at org.grobid.core.utilities.BibDataSetContextExtractor.extractContextSentence(BibDataSetContextExtractor.java:86)                                                                                                              
! at org.grobid.core.utilities.BibDataSetContextExtractor.getCitationReferences(BibDataSetContextExtractor.java:73) …
```
=> Fix BibDataSetContextExtractor to quote replacement text

grobid-core/src/main/java/org/grobid/core/layout/BoundingBox.java, grobid-core/src/main/java/org/grobid/core/visualization/CitationsVisualizer.java, grobid-core/src/test/java/org/grobid/core/visualization/TestCitationsVisualizer.java
The reference annotations endpoint returns invalid JSON when, for instance, a reference hyperlink in a PDF contains a backslash. Strings weren't being escaped before being put into the JSON response, so invalid backslash escape sequences could occur and cause parse errors.
This adds a test case and reimplements JSON generation using Jackson, which should avoid all such problems.
=> Fix JSON generation for reference annotations

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java
Current code sanitizes the emails but then assigns the unsanitized version to authorEmailAssigner. This change ensures that `sanitizedEmails` are correctly assigned.
=> Assign sanitizedEmails to authorEmailAssigner

build.gradle
This removes the downstream dependency on saxon9-dom.jar - see:
https://stackoverflow.com/a/15441957/9098739
=> Update Saxon 9 to a more recent version to remove dependency on saxon9-dom.jar

doc/Coordinates-in-PDF.md
These were the wrong way round.
Also – the "Edit on GitHub" button is broken in the docs. I couldn't find where that is configured in the repo, so I am guessing it is configured in the readthedocs web interface.
=> Swap w/h in coordinates documentation

Dockerfile
The latest version of openjdk:8-jre-slim doesn't include unzip anymore.
With the latest version
```console
$ docker pull openjdk:8-jre-slim
8-jre-slim: Pulling from library/openjdk
Digest: sha256:39bece5e977d0daeb0510335f2624b929f893c167a09e6fc4e28412bb78eeb90
Status: Image is up to date for openjdk:8-jre-slim
$ docker run --rm openjdk:8-jre-slim unzip -h
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"unzip\": executable file not found in $PATH": unknown.
```
Previous version:
```console
$ docker run --rm openjdk:8u131-jre-slim unzip -h
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
...
```
Fix:
- install `unzip`
- pin base image to avoid issue in the future (and make it more clear what the …
=> fixed docker build with latest openjdk:8-jre-slim image

grobid-core/src/main/java/org/grobid/core/jni/JEPThreadPool.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidPropertyKeys.java, grobid-core/src/test/java/org/grobid/core/utilities/GrobidPropertiesTest.java
This makes it easier to see what's going on with DeLFT (or Python) called by JEP.
=> optionally redirect jep output

grobid-core/src/main/java/org/grobid/core/jni/DeLFTModel.java
resolves #466 
This is a workaround for the issue. In most cases it will just set the value as before. In the odd case, it will write the data to a temp file and let Python load it from there.
=> added workaround for setting JEP value with very special characters

.gitignore
Visual Studio Code outputs to the `bin` folder. This would exclude those files from git (not sure if there would be any benefit of including it).
=> added bin to .gitignore

doc/Grobid-service.md, grobid-service/config/config.yaml, grobid-service/src/main/java/org/grobid/service/GrobidServicePropConfiguration.java, grobid-service/src/main/java/org/grobid/service/main/GrobidServiceApplication.java, grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java, grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessString.java
=> Cors configuration

grobid-service/src/test/resources/setup/config/test-config.yaml
The port 8075 and 8076 are more likely to be used by other services, when deployed in the same server, causing the tests to fail. I propose to modify them.
=> Change local unit tests server ports 

grobid-core/src/main/java/org/grobid/core/data/Table.java, grobid-core/src/main/java/org/grobid/core/data/table/Cell.java, grobid-core/src/main/java/org/grobid/core/data/table/Line.java, grobid-core/src/main/java/org/grobid/core/data/table/LinePart.java, grobid-core/src/main/java/org/grobid/core/data/table/Row.java
Algorithms for table parsing. Inspired by: http://ieg.ifs.tuwien.ac.at/projects/pdf2table/yildiz_iicai05.pdf
Particularly, I've implemented the first algorithm from there and the idea in general. I suppose it's called the line-based approach.  It works much better than tabula, as a minimum on my test instance. 
related to: 
https://github.com/kermitt2/grobid/issues/514
https://github.com/kermitt2/grobid/issues/340
Examples: https://vitaliy-1.github.io/tablesExample/
=> Parsing of table content

Readme.md
Number ranges are typeset in LaTeX using `number--number`. This is implemented here.
=> Fix LaTeX sytnax of year range

build.gradle, grobid-trainer/src/main/java/org/grobid/trainer/AbstractTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/TableTrainer.java
This PR allows to run the n-fold cross-validation of a specific model several times sharing the same grobid-home. 
Currently the models are named `model_name_nfold_x` with model_name corresponding the name of the model and x the n-ith fold. However if the same model is evaluated at the same time, they will write/overwrite the models in the `grobid-home/tmp` directory. 
This PR: 
- add a unique random string on the ith-fold model name
- collect generated files paths and deleted them at the end of the process
=> Remove side-effects when running several proceses of n-fold cross-validation of the same model while sharing the same grobid-home directory

doc/Grobid-docker.md, grobid-core/src/main/java/org/grobid/core/utilities/EnvironmentVariableProperties.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java, grobid-core/src/test/java/org/grobid/core/utilities/EnvironmentVariablePropertiesTest.java, grobid-core/src/test/java/org/grobid/core/utilities/GrobidPropertiesTest.java
implementation of first option discussed in #480
For example setting `GROBID__HEADER__USE_HEURISTICS=false` results in `grobid.header.use_heuristics: false`.
/cc @kermitt2
=> added support for environment variable overrides

grobid-service/src/main/resources/web/grobid/grobid.js
The button download tei did not work for text forms, because the filename was taken from the file upload input form
=> Fix the output filename wrongly taken from the input form when the text form is used

CHANGELOG.md
KeepAChangelog requires to have links in the header. This one adds it.
Furthermore, during development, there should be an `[Unreleased]` heading.
=> Add missing link

grobid-core/src/main/java/org/grobid/core/utilities/matching/ReferenceMarkerMatcher.java
Improve callout to reference match by removing parentheses often seen in callouts.
As seen in the docs, callouts often include parentheses.
https://grobid.readthedocs.io/en/latest/training/fulltext/
I saw many occasions that these parentheses prevent matching the correct references.
See the red boxes when trying arxiv.org/pdf/1801.01290.pdf
=> Improve callout to reference match

grobid-core/src/main/java/org/grobid/core/utilities/EnvironmentVariableProperties.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java, grobid-core/src/test/java/org/grobid/core/utilities/EnvironmentVariablePropertiesTest.java
Fixes: https://github.com/kermitt2/grobid/issues/608
This changes `EnvironmentVariableProperties` to allow passing in a regex instead of a prefix, allowing `GrobidProperties` to match both `ORG__GROBID__*` and `GROBID__` environment variables
=> Allow overriding org.* properties with env vars

grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java, grobid-core/src/main/java/org/grobid/core/utilities/crossref/CrossrefClient.java
I've noticed that when the title is supplied, grobid uses a deprecated field `query.title` (https://github.com/CrossRef/rest-api-doc#works-field-queries) instead of `query.bibliographic`. 
This results in a 400 Bad request from crossref, and the consolidation is not applied.
=> update call to crossref when title is supplied

build.gradle
quick "fix" for https://github.com/kermitt2/grobid/issues/628
This is to make it work again. We could optimise it later.
=> enabled service dist zip for docker build

build.gradle
This adds the `sentence-segmentation` folder to the Gradle package definition. Without this, sentence segmentation does not work inside the Docker container (as the Ruby source is not found).
=> Add "sentence-segmentation/**" to Gradle package

grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java
I've added two new methods in the GrobidProperties that allow to: 
- get all the engines selected individually in the configuration 
- get all possible engines needed (result of the above point  and the engine selected in the `grobid.crf.engine` property. 
When running LibraryLoader.load() instead of checking only the value of `grobid.crf.engine` I consider the list of specified engines.
=> Fixing problem in PR 559

grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java
When we invoke the static context of GrobidModels, all the models declared over there are loaded. Before applying #559 this was working without issues. 559 introduce a lookup on the properties that, at the time of the test is running are not loaded, therefore NPE. 
The first commit fixes right away the issue. However, I'm wondering whether we should have a completely different class for the DUMMY model, because if the test is ran from a directory that has no access to the grobid-home, I fear it will fail anyway.
=> NPE when Grobid is initialised from a module or test and the property file is not loaded yet (e.g. static context initialisation of GrobidModels)

grobid-core/src/main/java/org/grobid/core/jni/DeLFTModel.java
See [Mattermost conversation](https://traces1.inria.fr/mattermost/inria-rookies/pl/qhgkwxc9xjd33pip3whe1p6ksh)
When using a DL `fulltext` model, no `figure` and `table` data was generated.
That is because a tab is expected for the [figure data generation](https://github.com/kermitt2/grobid/blob/35c46b0f0db78dc775e5b76c025c9c9d53cf7af2/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L1958) and  [table data generation](https://github.com/kermitt2/grobid/blob/35c46b0f0db78dc775e5b76c025c9c9d53cf7af2/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L2119).
I haven't test it yet, but might be related to https://github.com/kermitt2/grobid/issues/470 (EDIT: no, doesn't seem to be resolved by this PR)
Since the `WapitiModel.label` function is already …
=> replaced space by tab in DeLFTModel.label

grobid-core/src/main/java/org/grobid/core/utilities/crossref/CrossrefRequest.java
CrossRef web API now request the metadata plus token to be put in Crossref-Plus-API-Token header:
https://github.com/CrossRef/rest-api-doc#authorization-token-for-plus-service
=> use Crossref-Plus-API-Token instead of Authorization

grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java
Continuation of #677 
I moved the check before labelling sequence for full-text, so that if there is no body all the subsequent chain in skipped.
=> Avoid NPE in FulltextParser when the body text is empty or null

grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java, grobid-core/src/main/java/org/grobid/core/engines/Engine.java, grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java, grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java, grobid-core/src/main/java/org/grobid/core/engines/patent/ReferenceExtractor.java, grobid-core/src/main/java/org/grobid/core/jni/DeLFTModel.java, grobid-trainer/doc/PMC_sample_1943.results.grobid-0.6.2-SNAPSHOT-Glutton-DeLFT-WAPITI-MIXED-BidLSTM-CRF-FEATURES-23.12.2020
With this PR (related to issue #665), sequences can now be grouped and passed in set to the sequence labeling algorithm. For the deep learning sequence labeling, batch of size runtime `batch_size` as defined in the DL model config are used as sequences are provided. For CRF, we simply apply the model to several sequences at the time, instead of one - but this is usual business. 
Grouping is at document-level, so this change won't improve sequences that are processed only one time per document (header, reference segmenter, fulltext, segmentation, header author name) - they will remain alone in their batch :) The improvement is relevant in practice to bibliographical references and affiliation+address blocks.
In this implementation, we modify the way the sequences are collected and we don't …
=> [WIP] Exploit batch processing for Deep Learning models

Dockerfile.crf
https://github.com/kermitt2/grobid/issues/697
Shrunk the container from 1.66 GB to 912.5 MB. Most of the change is achieved in the first commit, which maintains total parity of output with the previous version. Later commits are remove unused artifacts, volume, & disable logging into the container (which in production environments would cause it to fail over after running for long periods).
=> Dockerfile enhancements

grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java, grobid-core/src/test/java/org/grobid/core/engines/FullTextParserTest.java
Attempt to fix #693, and is valid for both figures and tables.
One case is when only one figure/table is identified in the fulltext, it is not output in the respective training data.
The fix attempt to verify that there are not figure/tables accumulated but not consumed
To reproduce the behaviour as explained in #693 is necessary to merge here the `features/add-training-data` or use the branch `bugfix/fix-figure-table-training-data-generation`
=> Generation of training data for tables and figures outputs less element than in input 

build.gradle, grobid-core/src/test/java/org/grobid/core/utilities/SentenceUtilitiesTest.java
I'm adding more tests for testing that the sentence segmentation correction works fine. 
Actually I though there was a bug, but then after I've added tests I realised it was fine. The tests have more realistic examples and they allow to be independent than the sentence segmenter (which might change the results in future).
=> Add more tests on sentence segmentation

Dockerfile.delft, doc/Grobid-docker.md
I tried to adapt the change to the CRF-only dockerfile to the one using DeLFT, see PR #703 . This is reducing the image in a similar manner from 10.3GB to 9.8GB, but of course this is less impressive at this scale :)
Still using JRE 8 in the current form.
=> Aligned Deep Learning Dockerfile with PR #703

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java, grobid-core/src/main/java/org/grobid/core/document/Document.java, grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java, grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java, grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java
In this PR, I 
~~- added a method to fill up the layoutTokens map that contains the layout tokens of the various component (title, abstract, etc..) and it's filled up when the clusteror is processed~~
~~- added getter of `titleLayoutToken`, `abstractLayoutToken` and `authorsLayoutToken` lists. 
(probably these two items are duplicated but they are used in different part so I did not feel like to remove one of them...~~
- call the method `generalResultMapping()` in `resultExtraction` of HeaderParser 
- remove lists of layout tokens for abstract, title and authors, from the BiblioItem class
- various cosmetic improvements, removed some not-needed nulls-checks
- removed unused parameters in certain methods
- added a way to better understand the exception when calling glutton 
The use case is …
=> Finalize getting Layout token lists for header fields

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java, grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java, grobid-core/src/main/java/org/grobid/core/engines/Engine.java, grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java, grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java, grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java, grobid-core/src/main/java/org/grobid/core/utilities/glutton/GluttonClient.java, grobid-core/src/test/java/org/grobid/core/data/BiblioItemTest.java, grobid-core/src/test/java/org/grobid/core/utilities/ConsolidationTest.java
As mentioned in https://github.com/kermitt2/biblio-glutton/issues/55 
When I wrote the test I realised that the result of `substring()`, aiming at removing the prefix, was not used. 
This should: 
- remove diactric (not sure is needed)
- remove characther that combined with others 
- fix substring(4) using the 
About diactricts: https://memorynotfound.com/remove-accents-diacritics-from-string/
=> improving methods that clean doi for consolidation

grobid-core/src/main/java/org/grobid/core/document/Document.java, grobid-core/src/main/java/org/grobid/core/document/DocumentSource.java, grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java, grobid-core/src/main/java/org/grobid/core/engines/Engine.java, grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java, grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java, grobid-core/src/main/java/org/grobid/core/engines/ProcessEngine.java, grobid-core/src/main/java/org/grobid/core/visualization/BlockVisualizer.java, grobid-core/src/test/java/org/grobid/core/engines/EngineTest.java, grobid-core/src/test/java/org/grobid/core/test/TestFullTextParser.java, grobid-core/src/test/java/org/grobid/core/visualization/TestCitationsVisualizer.java, grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java
Compute the MD5 digest of a PDF file processed by the web services and add it in the resulting TEI.
see #740
MD5 is processed when the file is loaded by the service (very nice feature of Java!). To avoid reading an extra time the PDF files, we don't compute MD5 digests for the batch/command lines, so it's a web service only feature.
=> Add MD5 for PDF files 

CHANGELOG.md
This PR fixes the links in the headers - and the release date of 0.6.2 and 0.7.0.
=> Fix changelog (links + date)

.circleci/config.yml, grobid-service/src/test/java/org/grobid/service/tests/GrobidRestServiceTest.java
This PR adds the configuration for building the project with circleci. It requires the grobid project to be enabled from circleci from the owner.
=> Migrate to circle CI  

grobid-core/src/main/java/org/grobid/core/utilities/crossref/WorkDeserializer.java
Minor bugfix. The day (String only) in the consolidated date was not correctly assigned from the response.
=> fix deserialised consolidation day

grobid-trainer/resources/dataset/name/citation/corpus/author.tei.xml
When skimming over TEI training data (to see how diverse the source data is), I noticed what seem to be two small labeling errors.
I checked over the rest of this file (author.tei.xml), but didn't inspect the rest of the citation corpus carefully.
=> training: small fixes to name (citation) data

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java
Closes: https://github.com/kermitt2/grobid/issues/845
Tested with the string mentioned in the issue, but didn't add any unit test coverage.
=> TEI: multiple editors each get <editor> around <persName>

grobid-core/src/main/java/org/grobid/core/visualization/CitationsVisualizer.java
Small tweak to use a more direct URL for arxiv.org preprints
=> visualizer: use arxiv.org/abs/<id> instead of arxiv.org/<id>

grobid-core/src/main/java/org/grobid/core/engines/citations/CalloutAnalyzer.java, grobid-core/src/test/java/org/grobid/core/engines/citations/CalloutAnalyzerTest.java
Try to fix issue #867 with atomic grouping, avoiding normally possible catastrophic backtracking.
Add some pretty useless tests, giving false confidence that nothing bad could happen.
=> Fix regex, #867

.circleci/config.yml, build.gradle
To avoid #822 at the next Gradle build update
Since I had to push some tests, this PR can be squashed in a single commit so that it will appear only as the change in the circleci configuration
=> Add assemble build task to CI 

grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java, grobid-core/src/main/java/org/grobid/core/utilities/IOUtilities.java, grobid-core/src/main/java/org/grobid/core/utilities/TextUtilities.java, grobid-home/config/grobid.yaml, grobid-home/config/resources-registry.json
This PR allows to use the temporary directory as it is (without concatenation to the grobid-home) when the specified directory is an absolute path.
=> Allow absolute paths in temporary directory configuration 

grobid-core/src/main/java/org/grobid/core/document/DocumentSource.java, grobid-core/src/main/java/org/grobid/core/utilities/GrobidProperties.java, grobid-home/pdfalto/lin-64/pdfalto_server, grobid-home/pdfalto/mac-64/pdfalto_server
This PR should add a dynamic timeout on the pdfalto_server script using the argument `--timeout XY`. #923 
It also avoid changing the virtual memory on mac Os. #894
=> Add dynamic timeout on pdfalto_server

grobid-core/src/main/java/org/grobid/core/jni/DeLFTClassifierModel.java, grobid-core/src/main/java/org/grobid/core/jni/DeLFTModel.java, grobid-core/src/main/java/org/grobid/core/jni/JEPThreadPool.java, grobid-core/src/main/java/org/grobid/core/jni/JEPThreadPoolClassifier.java, grobid-core/src/main/java/org/grobid/core/main/LibraryLoader.java
This PR tries to show an error at startup when JEP is not correctly initialised: 
For example: 
```
INFO  [2022-08-09 14:23:57,617] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for quantities with architecture BidLSTM_CRF...
running thread: 1
INFO  [2022-08-09 14:23:57,623] org.grobid.core.jni.JEPThreadPool: Creating JEP instance for thread 16
ERROR [2022-08-09 14:23:57,633] org.grobid.core.jni.JEPThreadPool: JEP initialisation failed somewhere.
```
The startup will continue, however at least there is a trace in the log file.
=> Improve JEP initialisation and DL model loading error logging

doc/Grobid-service.md, doc/Training-the-models-of-Grobid.md, grobid-core/src/main/java/org/grobid/core/jni/DeLFTClassifierModel.java, grobid-core/src/main/java/org/grobid/core/jni/DeLFTModel.java, grobid-core/src/test/java/org/grobid/core/test/TestHeaderParser.java, grobid-service/src/main/java/org/grobid/service/GrobidRestService.java, grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessTraining.java, grobid-trainer/src/main/java/org/grobid/trainer/AbstractTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/CRFPPGenericTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/DeLFTTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/DummyTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/GenericTrainer.java, grobid-trainer/src/main/java/org/grobid/trainer/Trainer.java, grobid-trainer/src/main/java/org/grobid/trainer/TrainerRunner.java, grobid-trainer/src/main/java/org/grobid/trainer/WapitiTrainer.java
Support incremental training for Deep Learning models. 
We simply add `-i` to the training command, and the training will resume from the existing model instead of starting from scratch with a new model.
```bash
> java -Xmx1024m -jar grobid-trainer/build/libs/grobid-trainer-<current version>-onejar.jar 0 <name of the model> -gH grobid-home -i
``` 
See https://github.com/kermitt2/delft/pull/147 
It does work for CRF Wapiti too.
=> Incremental training for Deep Learning and Wapiti models

Dockerfile.crf, Dockerfile.delft
Remove the mac arm libraries from the linux-based docker images. 
Until we build a multi-arch image we don't need these libraries to be there.
=> Minor update to the docker images

grobid-core/src/main/java/org/grobid/core/document/DocumentSource.java, grobid-home/pdfalto/lin-64/pdfalto_server, grobid-home/pdfalto/mac-64/pdfalto_server
This is a fix for #1036 
The memory limit for the pdfalto subprocess was only set for batch mode, not for server mode. 
This PR pass the memory limit defined in the Grobid configuration file to the `pdfalto_server` script, which set the ulimit before creating the pdfalto subprocess. 
Tested successfully with the java server. 
todo: to be tested with Docker.
=> Set dynamic memory limit in pdfalto_server

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java, grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/main/java/org/grobid/core/engines/ProcessEngine.java, grobid-service/src/main/resources/web/grobid/grobid.js
The attribute for the coordinates in titles is 'coord' instead of 'coords'. 
I assume it was a typo, and it should be consistent with the rest of the TEI output, anyway it was easier to submit a PR than to ask first :smile:
=> correct <title> coordinates attribute name

.github/workflows/ci-build-unstable.yml, grobid-core/src/main/java/org/grobid/core/data/Note.java, grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/test/java/org/grobid/core/document/TEIFormatterTest.java
This PR should solve issue #1073. 🎉 
The de-hyphenation made the two streams (noteTokens) and footText de-synchronised. I moved at the end of the process. 
I've also renamed a few variables and tide up a bit in the effort of following the flow in this complex process 😅
=> Fix OOBE when processing large quantities of notes

grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-service/src/main/resources/web/grobid/grobid.js
When the paragraph continues after interruption (e.g., reference callout), the coordinates are lost: 
This PR solves this issue. 
This PR also adds a small modification in the frontend so that the paragraph coordinates are extracted if "add coordinates" is selected and "segment sentence" is not selected.
=> Fix missing coordinates in paragraphs continuation 

Dockerfile.delft
This PR attempts to reduce the docker image by reducing the number of layers. 
By just chancing the layers, I managed to save 700Mb. We could optimise more in future, especially considering that grobid modules (e.g. grobid-quantities) are not able to build properly at the moment, on github actions (limited to ~20Gb). 
One solution would be to move everything in the build and then just copy the resulting files in the tensorflow image. 
I also noticed that the delft used here is 0.3.3, I'm not sure whether it's by design, I propose to update it to 0.3.4.
=> Reduce docker image size for the NN grobid version 

.github/workflows/ci-build-manual.yml, .github/workflows/ci-build-unstable.yml
This PR will extend the current github actions: 
- The automatic build only produce the CRF-only image (`latest-develop`)
- We added a manual build that will push both CRF-only (tags `latest-develop`, `latest-crf`) and the delft full image (tag `latest-full`) . The user can select any branch, this is useful for testing specific features.
=> Add additional github actions

grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
More details are in #1113. 
TLDR: 
- avoid collecting the same position in the text when the note label is the same. So for example if we have `This note1, and this note2, but back to the first note1`, we would collect twice the offset of the first 1 label.
- update the labels2notes so that we use the identifier instead.
- fix a NPE when the note tokenization are empty, the processShort return a null, so we skip such note
=> fix notes identification

grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java
=> Fix issue #1130

Dockerfile.delft, grobid-home/config/grobid-full.yaml, grobid-home/config/resources-registry.json
This PR provide a configuration file with the recommended deep learning models enabled. Each docker image is then reproducible directly in github actions. 
in the last days the GloVE embeddings URL was not available, so I changed with the huggingface repository which should be more reliable. 
@kermitt2 a question, for the copyright and licence, should we enable them by default?
=> Specify configuration file with DL models enabled for the full docker image

Dockerfile.crf
There are still 46 high- and 11 critical-level vulnerabilities in the "latest:crf" tag. this should apply the patches for these vulnerabilities.
=> adding apt-get upgrade in  the builder image

grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java, grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java, grobid-core/src/main/java/org/grobid/core/utilities/crossref/WorkDeserializer.java, grobid-core/src/main/java/org/grobid/core/utilities/glutton/GluttonRequest.java
This PR enables the support of the latest version of biblio-glutton (0.3), which extends the bibliographical reference matching to HAL archive (around 3.5M records), beyond CrossRef records with DOI. 
In practice, consolidation can now resolve raw bibliographical references against HAL records, in case it is not present in Crossref. HAL ID are also added when we have a DOI matching for a record also present on HAL.
For example, with the PDF https://hal.science/hal-04303155v2, we have several consolidated entries with HAL ID and no DOI in the bibliographical reference section:
```
<biblStruct xml:id="b14">
<analytic>
<title level="a" type="main">Grafting of nitrophenyl groups on carbon and metallic surfaces without electrochemical induction</title>
<author>
<persName>
<forename …
```
=> Support for biblio-glutton 0.3

grobid-core/src/main/java/org/grobid/core/engines/AffiliationAddressParser.java, grobid-core/src/test/java/org/grobid/core/engines/AffiliationAddressParserTest.java
This PR propose a fix for the affiliation, that are lost when processing them with a DL model. 
The issue seems to be in the method: `getAffiliationBlocksFromSegments()` where new `\n` are added (in general they should be added if there is a misalignment, however they are added for sure at the beginning). 
https://github.com/kermitt2/grobid/blob/a95d2533f1019e900b49ea5c39a5afe355dbb4a3/grobid-core/src/main/java/org/grobid/core/engines/AffiliationAddressParser.java#L81
I patched quickly by checking that `end` is not zero. However this `\n` does not work well with the DL models, at contrary with the CRF models that they are ignoring it. 
I've left two tests which are showing the problem from both CRF and DL: https://github.com/kermitt2/grobid/blob/bd93a61f4542f218299e2c34a82c37b75bc727ef/gro …
=> Fix affiliation missing when using DL affiliation-address model

Dockerfile.delft
This PR fixes an issue where apt-get upgrade was upgrading CUDA from 11.2 to 12.2, causing mismatches between libcublas 11.2, libcudnn8, and other GPU libraries. This led to GPU-related errors in production.
Changes:
Held back library _libcudnn8_ to prevent it from upgrading to CUDA 12.2.
=> hold cuda11.2 from upgrading to cuda12.2

grobid-trainer/resources/dataset/fulltext/corpus/tei/s41598-020-58065-9.training.fulltext.tei.xml
Corrections following the annotation guide: https://grobid.readthedocs.io/en/latest/training/fulltext/#formulas
=> Move brackets out of labels in formulas

grobid-core/src/main/java/org/grobid/core/document/OPSService.java, grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessTraining.java
Fixes [https://github.com/kermitt2/grobid/security/code-scanning/41](https://github.com/kermitt2/grobid/security/code-scanning/41)
To fix the problem, we need to ensure that the XML parser is fully secured against XXE attacks. This involves:
1. Ensuring that the `SAXParserFactory` is configured to disallow DTDs.
2. Ensuring that the `XMLReader` is configured to disallow external entities.
3. Adding an `EntityResolver` that returns an empty string for any external entity.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 41: Resolving XML external entity in user-controlled data

grobid-service/src/main/java/org/grobid/service/util/ZipUtils.java
Fixes [https://github.com/kermitt2/grobid/security/code-scanning/61](https://github.com/kermitt2/grobid/security/code-scanning/61)
To fix the problem, we need to ensure that the output paths constructed from zip archive entries are validated to prevent writing files to unexpected locations. This can be done by verifying that the normalized full path of the output file starts with a prefix that matches the destination directory. We will use `java.nio.file.Path` for path normalization and prefix checking.
1. Normalize the path of the file to be created.
2. Check if the normalized path starts with the destination directory path.
3. If the check fails, throw an exception to prevent writing the file.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 61: Arbitrary file access during archive extraction ("Zip Slip")

grobid-core/src/main/java/org/grobid/core/main/GrobidHomeFinder.java
Fixes [https://github.com/kermitt2/grobid/security/code-scanning/39](https://github.com/kermitt2/grobid/security/code-scanning/39)
To fix the problem, we need to ensure that the file paths constructed from zip entries are validated to prevent writing files to unexpected locations. This can be achieved by normalizing the file paths and ensuring they start with the intended destination directory.
1. Normalize the file path using `toPath().normalize()`.
2. Check if the normalized path starts with the destination directory path using `startsWith()`.
3. If the check fails, throw an exception to prevent writing the file.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 39: Arbitrary file access during archive extraction ("Zip Slip")

build.gradle, grobid-core/src/main/java/org/grobid/core/analyzers/GrobidAnalyzer.java, grobid-core/src/main/java/org/grobid/core/engines/tagging/GenericTaggerUtils.java
Use a repackaged and cleaned Lucene CJK analyzers for GROBID.
=> Updated Grobid lucene analyzers for CJK languages

grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
This PR extend the attempt to retrieve text when the document does not have enought, this is normally due to documents that re not scientific articles.
=> Avoid running aground when detecting the language

grobid-core/src/main/java/org/grobid/core/data/Table.java
This PR fixes #1232. However to test it is necessary to apply this patch to the tag 0.8.1 because with the master version the PDF provided in 1232 does not present the problem because many mis-classified tables (including the one causing the issue) are reverted back to paragraph.
=> Fix the way table notes are streamed on the XML

grobid-trainer/resources/dataset/fulltext/evaluation/tei/PMC2644281.training.fulltext.tei.xml
`<head>Methods<lb/> Preparation<lb/></head>` are actually two headings in the original paper.
=> Fix heading annotation in fulltext evaluation and add header levels

grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/test/java/org/grobid/core/document/TEIFormatterTest.java
This PR fixes issues #1233 (the part related to the reference construction), #1244, and #1175. 
The issue happens when the reference markers labels are partially correct, for example the reference is `and 3C` with the first reference which is wrongly classified.
=> Avoid empty figures/tables reference markers

grobid-core/src/main/java/org/grobid/core/data/Table.java
Table notes seems to have missing sentence when requested. Probably a regression from #1232
=> Fix missing sentence segmentation for table notes

.github/workflows/ci-build-manual-eval.yml, Dockerfile.evaluation, grobid-home/config/grobid-evaluation.yaml
This PR finalize the first version of the end to end evaluation docker image. The image can be run locally, and it requires an instance of biblio-glutton. 
A working example can be found on [huggingface](https://huggingface.co/spaces/lfoppiano/grobid-evaluation)
=> End to end evaluation docker image follow-up

.github/ISSUE_TEMPLATE/general-report.yml, Dockerfile.crf, Dockerfile.delft, Dockerfile.evaluation
Added ARCH ARG argument to allow overriding of the architecture using '--build-arg ARCH=<ARCH>', defaulting to 'amd64'.
For CRF amd64 :-
```
docker build -t grobid/grobid:0.8.2-SNAPSHOT --build-arg GROBID_VERSION=0.8.2-SNAPSHOT --file Dockerfile.crf .
```
For CRF arm64 :-
```
docker build -t grobid/grobid:0.8.2-SNAPSHOT --build-arg GROBID_VERSION=0.8.2-SNAPSHOT --build-arg ARCH=arm64 --file Dockerfile.crf .
```
For DELFT amd64 :-
```
docker build -t grobid/grobid:0.8.2-SNAPSHOT --build-arg GROBID_VERSION=0.8.2-SNAPSHOT --file Dockerfile.delft .
```
For DELFT arm64 :-
```
docker build -t grobid/grobid:0.8.2-SNAPSHOT --build-arg GROBID_VERSION=0.8.2-SNAPSHOT --build-arg ARCH=arm64 --file Dockerfile.delft .
```
=> Add ARCH ARG for '--build-arg ARCH=<ARCH>', defaulting to 'amd64'.

Dockerfile.delft
Reducing the docker image by avoiding the pip cache
=> avoid creating pip cache

grobid-core/src/main/java/org/grobid/core/data/Person.java, grobid-core/src/main/java/org/grobid/core/engines/AuthorParser.java, grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java
Causes: 
- in the case of the ORCID PDF Annotation is placed on top of the author names the authors names are lost (Example [hal-03664928_v1_main.pdf](https://github.com/user-attachments/files/19795155/hal-03664928_v1_main.pdf))
- in the case whether the authors are not extracted correctly from the PDF (Example:  [hal-01859106_v1_main_Gimello_Georges_Delerue_une_vie_texte1.pdf](https://github.com/user-attachments/files/19795175/hal-01859106_v1_main_Gimello_Georges_Delerue_une_vie_texte1.pdf)
=> Avoid NPE when the authors names are empty or null

grobid-core/src/main/java/org/grobid/core/data/FigureTableType.java, grobid-core/src/main/java/org/grobid/core/document/TEIFormatter.java, grobid-core/src/main/java/org/grobid/core/utilities/matching/ReferenceMarkerMatcher.java, grobid-core/src/test/java/org/grobid/core/document/TEIFormatterTest.java
This PR extends https://github.com/kermitt2/grobid/pull/1246 by including `,` as reference separator. 
We also simplify the creation of the table and figure reference in a single method with the "type" as discriminant to avoid divergent methods
=> Fix invalid figure reference when punctuation comma are left inside

build.gradle, grobid-home/sentence-segmentation/pragmatic_segmenter/abbreviation_replacer.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/cleaner.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/languages/common/numbers.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/languages/deutsch.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/languages/japanese.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/languages/kazakh.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/list.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/processor.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/punctuation_replacer.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/types.rb, grobid-home/sentence-segmentation/pragmatic_segmenter/version.rb
This PR fixes the regression introduced by updating to jruby 9.4.12.0 (in #1261): 
- update JRUBY 
- update pragmatic segmenter to 0.3.24
More tests are required, ideally a few thousand PDFs. Before testing, you have to switch to the pragmatic segmenter in the configuration: 
```
sentenceDetectorFactory: "org.grobid.core.lang.impl.PragmaticSentenceDetectorFactory"
```
=> Update jruby to 9.4.12.1
